---
version: '3'

vars:
  SOURCE_FOLDER: src

tasks:
  default:
    cmds:
      - task: test
      - task: build

  mod:
    desc: update go modules, add submodules to go root
    cmds:
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_add_sub_packages.sh | bash

  prep:
    cmds:
      - cmd: cp examples/p2r.yaml src/conf/

  build:
    desc: build binary using remote ghwfe script, requires curl
    cmds:
      - task: prep
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_build.sh | bash

  test:
    desc: run go tests
    sources:
      - "{{.SOURCE_FOLDER}}/*"
    method: timestamp
    cmds:
      - task: prep
      - cmd: >-
          go test -trace go.trace -race -cover -bench=. {{.SOURCE_FOLDER}}/*.go

  deploy:
    desc: build and copy to my personal arch mybins folder
    cmds:
      - task: build
      - cmd: cp -rpf build/* ${HOME}/tools/arch/mybins/
